<?php include_once "header.phtml"; ?>
<?php include_once "utils.php"; ?>

<div class="kk">
<form method="get">
<input type="text" name="fraze" placeholder="fraze" value="labas">
<select id="kalba" name="kalba">
      <option value="EN">LT to EN</option>
      <option value="LT">EN to LT</option>
</select>
<input type="submit" value="translate">
</form>


<h2><?php echo $zodis ?></h2>

</div>

<?php include_once "footer.phtml"; ?>
