
<br>
  <form method="post">
   <b>To do:</b> <input type="text" name="vardas" placeholder="cool staf">
   <!-- Last name:<input type="text" name="pavarde" placeholder="Last name"><br> -->
<input type="date" name="laikas" value="2017-02-03" placeholder="laikas irasomas ranka" required><br>

<label>
 <input type="radio" value="low" id="low" name="nu" required>:Low
</label>
<label>
<input type="radio" value="normal" id="normal" name="nu" required checked>:Normal
</label>
<label>
 <input type="radio" value="high" id="high" name="nu" required>:High
</label>
<br>


<textarea rows="5" cols="80" name="textas" placeholder="komentarai"></textarea></br>
<input type="submit" value="Append">
<br>



 </form>
