
<html>
<head>
  <meta charset="utf-8">
  <title><?php print $day.$title ?></title>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="diena.css"/>
  <link href="https://fonts.googleapis.com/css?family=Courgette|Gloria+Hallelujah&amp;subset=latin-ext" rel="stylesheet">
</head>
<body>

<h1>Pamoka: <?php echo $day ?></h1>
