<table border="1px">
  <thead>
    <tr >
      <th colspan="2"> lenteles pavadinimas</th>
    </tr>
  </thead>
<tr><td>1 aaaaaaaaaaa</td><td>bbbbbbb 1</td></tr>
<tr><td>2 aaaaaaaaaaa</td><td>bbbbbbb 2</td></tr>
<tr><td>3 aaaaaaaaaaa</td><td>bbbbbbb 3</td></tr>
<tr><td>4 aaaaaaaaaaa</td><td>bbbbbbb 4</td></tr>
</table>




<table border="1px">
<tr>
<?php foreach ($table["head"] as $key): ?>
        <td> <?php echo $key; ?></td>
<?php endforeach; ?>
</tr>


<?php foreach ($table["body"] as $col):  ?>
<tr>
        <td><?php echo $col[0]; ?></td>
        <td><?php echo $col[1]; ?></td>
</tr>
<?php endforeach; ?>
</table>
