<!DOCTYPE HTML>
<html lang="en"> 
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title> 30diena <?=$procukt['productCode']?></title>
	<link rel="stylesheet" type="text/css" href="normalize.css"/>
	<!-- <link rel="stylesheet" type="text/css" href="bootstrap.css"/> -->
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
	<!-- <link rel="stylesheet" type="text/css" href="reset.css"/> -->
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="css/address-book.css">
	
	  <!-- jQuery library-->
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

    <!-- Utilities -->
    

    <!-- Address book methods -->
    
	<link rel="stylesheet" type="text/css" href="diena30.css"/>

</head>


<body>

<h1>Name: <?php echo $product['productName']?></h1>
<p> Code:<?php echo $product['productCode']?></p>
<p> Vendor:<?php echo $product['productVendor']?></p>
<p> Price:<?php echo $product['buyPrice']?></p>


</body>